import './style.css';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, Check, Clipboard, FileCode2, Gauge, Plus, RadioTower, RefreshCw, Send, Server, ShieldAlert, Trash2, Upload } from 'lucide-react';
import { apiDelete, apiGet, apiPost, apiPut } from '../../../frontend/src/api/client';

const base = '/api/tools/clash-subscription-manager';
type View = 'dashboard' | 'sources' | 'nodes' | 'profiles' | 'rules';
type Source = { id: string; name: string; url: string; refreshSeconds: number; enabled: boolean; status: string; lastSuccessAt?: string; lastError?: string };
type Node = { id: string; stableIdentity: string; name: string; protocol: string; server: string; port?: number; sources: string[]; supportedOutput: boolean; tcp?: { reachable: boolean; latencyMs?: number; error?: string } };
type RuleSet = { id: string; name: string; rules: unknown[]; providers: Record<string, unknown>; groups: { name: string; type?: string; proxies?: string[] }[] };
type Profile = { id: string; name: string; targetKernel: 'mihomo' | 'clash'; ruleSetId?: string; selectedStableIdentities?: string[]; publishedAt?: string; publishedStatus: string; validation: { level: string; message: string }[]; subscriptionToken?: string };
type Dashboard = { metrics: Record<string, number>; protocolDistribution: { name: string; value: number }[]; sources: Source[]; profiles: Profile[]; alerts: { message: string }[] };

export default function ClashSubscriptionManager() {
  const [view, setView] = useState<View>('dashboard');
  const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [sources, setSources] = useState<Source[]>([]); const [nodes, setNodes] = useState<Node[]>([]);
  const [profiles, setProfiles] = useState<Profile[]>([]); const [ruleSets, setRuleSets] = useState<RuleSet[]>([]);
  const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [sourceForm, setSourceForm] = useState({ name: '', url: '', refreshSeconds: 21600 });
  const [profileForm, setProfileForm] = useState({ name: '', targetKernel: 'mihomo' as 'mihomo' | 'clash' });
  const [search, setSearch] = useState(''); const [selected, setSelected] = useState<string[]>([]);

  const reload = async () => {
    try {
      const [d, s, n, p, r] = await Promise.all([
        apiGet<Dashboard>(`${base}/dashboard`), apiGet<{ sources: Source[] }>(`${base}/sources`), apiGet<{ nodes: Node[] }>(`${base}/nodes`), apiGet<{ profiles: Profile[] }>(`${base}/profiles`), apiGet<{ ruleSets: RuleSet[] }>(`${base}/rule-sets`),
      ]);
      setDashboard(d); setSources(s.sources); setNodes(n.nodes); setProfiles(p.profiles); setRuleSets(r.ruleSets); setError('');
    } catch (err) { setError(err instanceof Error ? err.message : '加载失败'); }
  };
  useEffect(() => { void reload(); }, []);
  const filteredNodes = useMemo(() => nodes.filter(node => `${node.name} ${node.server} ${node.protocol}`.toLowerCase().includes(search.toLowerCase())), [nodes, search]);
  const call = async (work: () => Promise<unknown>, message: string) => { try { await work(); setNotice(message); await reload(); } catch (err) { setError(err instanceof Error ? err.message : '操作失败'); } };
  const addSource = (event: FormEvent) => { event.preventDefault(); void call(async () => { await apiPost(`${base}/sources`, sourceForm); setSourceForm({ name: '', url: '', refreshSeconds: 21600 }); }, '订阅源已添加。'); };
  const addProfile = (event: FormEvent) => { event.preventDefault(); void call(async () => { await apiPost(`${base}/profiles`, profileForm); setProfileForm({ name: '', targetKernel: 'mihomo' }); }, '聚合配置已创建。'); };
  const copy = async (text: string, message = '已复制。') => { await navigator.clipboard.writeText(text); setNotice(message); };
  const subscribeUrl = (token?: string) => token ? `${window.location.origin}/sub/clash/${token}` : '';

  return <main className="csm-shell">
    <aside className="csm-sidebar"><div className="csm-brand"><RadioTower /> <span>Clash 聚合器</span></div>
      {([['dashboard', '运营总览', Gauge], ['sources', '订阅源', Server], ['nodes', '节点池', Activity], ['profiles', '聚合配置', Send], ['rules', '规则库与记录', FileCode2]] as const).map(([id, label, Icon]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}><Icon />{label}</button>)}
      <small>TCP 可达不代表代理可用或真实延迟。</small>
    </aside>
    <section className="csm-content"><header><div><h1>{({ dashboard: '运营总览', sources: '订阅源', nodes: '节点池', profiles: '聚合配置', rules: '规则库与刷新记录' } as Record<View, string>)[view]}</h1><p>用户级隔离 · 最后一次有效配置会持续对外提供</p></div><button className="csm-icon" title="刷新数据" onClick={() => void reload()}><RefreshCw /></button></header>
      {error && <div className="csm-message error"><AlertTriangle />{error}<button onClick={() => setError('')}>×</button></div>}
      {notice && <div className="csm-message ok"><Check />{notice}<button onClick={() => setNotice('')}>×</button></div>}
      {view === 'dashboard' && <DashboardView data={dashboard} go={setView} />}
      {view === 'sources' && <section className="csm-grid two"><form className="csm-card csm-form" onSubmit={addSource}><h2><Plus />添加订阅源</h2><label>名称<input value={sourceForm.name} onChange={e => setSourceForm({ ...sourceForm, name: e.target.value })} placeholder="例如：机场主订阅" /></label><label>HTTP(S) 地址<input required type="url" value={sourceForm.url} onChange={e => setSourceForm({ ...sourceForm, url: e.target.value })} placeholder="https://example.com/sub" /></label><label>刷新间隔（秒）<input type="number" min="60" value={sourceForm.refreshSeconds} onChange={e => setSourceForm({ ...sourceForm, refreshSeconds: Number(e.target.value) })} /></label><button className="primary"><Plus />添加</button></form><div className="csm-card"><h2>来源健康</h2><div className="csm-list">{sources.map(source => <article key={source.id}><div><strong>{source.name}</strong><small>{source.url}</small><small>{source.lastError || `上次成功：${pretty(source.lastSuccessAt)}`}</small></div><span className={`pill ${source.status}`}>{source.status === 'healthy' ? '正常' : source.status === 'error' ? '异常' : '未刷新'}</span><button title="立即刷新" onClick={() => void call(() => apiPost(`${base}/sources/${source.id}/refresh`, {}), '刷新完成。')}><RefreshCw /></button><button title="删除" className="danger" onClick={() => void call(() => apiDelete(`${base}/sources/${source.id}`), '订阅源已删除。')}><Trash2 /></button></article>)}{!sources.length && <Empty text="尚未添加订阅源。" />}</div></div></section>}
      {view === 'nodes' && <section className="csm-card"><div className="csm-toolbar"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="按名称、地址或协议搜索" /><button onClick={() => void call(() => apiPost(`${base}/nodes/probe`, { nodeIds: selected.length ? selected : filteredNodes.map(n => n.id) }), 'TCP 探测已完成。')}><Activity />探测{selected.length ? ` (${selected.length})` : '全部'}</button></div><div className="csm-table"><div className="head"><span></span><span>节点 / 来源</span><span>协议</span><span>端点</span><span>TCP</span></div>{filteredNodes.map(node => <label className="row" key={node.id}><input type="checkbox" checked={selected.includes(node.id)} onChange={e => setSelected(e.target.checked ? [...selected, node.id] : selected.filter(id => id !== node.id))} /><span><strong>{node.name}</strong><small>{node.sources.join(' · ') || '未知来源'} {!node.supportedOutput && ' · 不支持输出'}</small></span><code>{node.protocol}</code><span>{node.server}:{node.port || '—'}</span><span className={node.tcp?.reachable ? 'reachable' : 'muted'}>{node.tcp ? node.tcp.reachable ? `可达 ${node.tcp.latencyMs ?? ''}ms` : `失败 ${node.tcp.error || ''}` : '未探测'}</span></label>)}{!filteredNodes.length && <Empty text="节点会在成功刷新订阅源后出现。" />}</div></section>}
      {view === 'profiles' && <section className="csm-grid two"><form className="csm-card csm-form" onSubmit={addProfile}><h2><Plus />新建聚合配置</h2><label>名称<input required value={profileForm.name} onChange={e => setProfileForm({ ...profileForm, name: e.target.value })} placeholder="我的 Mihomo 订阅" /></label><label>目标内核<select value={profileForm.targetKernel} onChange={e => setProfileForm({ ...profileForm, targetKernel: e.target.value as 'mihomo' | 'clash' })}><option value="mihomo">Mihomo / Clash Meta</option><option value="clash">传统 Clash Premium</option></select></label><button className="primary"><Plus />创建</button></form><div className="csm-card"><h2>发布状态</h2><div className="csm-list">{profiles.map(profile => <ProfileCard key={profile.id} profile={profile} nodes={nodes} ruleSets={ruleSets} action={call} copy={copy} subscribeUrl={subscribeUrl} />)}{!profiles.length && <Empty text="创建配置后，选择节点、导入规则并校验发布。" />}</div></div></section>}
      {view === 'rules' && <RulesView ruleSets={ruleSets} action={call} />}
    </section>
  </main>;
}

function DashboardView({ data, go }: { data: Dashboard | null; go: (view: View) => void }) { const m = data?.metrics || {}; return <><section className="csm-metrics">{[['订阅源', m.sources, 'sources'], ['正常来源', m.healthySources, 'sources'], ['去重后节点', m.nodes, 'nodes'], ['TCP 可达', m.tcpReachable, 'nodes'], ['已发布配置', m.publishedProfiles, 'profiles'], ['待处理告警', m.alerts, 'profiles']].map(([label, value, target]) => <button key={String(label)} onClick={() => go(target as View)}><span>{label}</span><strong>{value ?? 0}</strong></button>)}</section><section className="csm-grid two"><div className="csm-card"><h2>节点协议分布</h2>{data?.protocolDistribution.map(item => <div className="bar" key={item.name}><code>{item.name}</code><i style={{ width: `${Math.max(8, Math.min(100, item.value * 12))}%` }}></i><b>{item.value}</b></div>) || <Empty text="暂无节点数据。" />}</div><div className="csm-card"><h2>告警中心</h2>{data?.alerts.length ? data.alerts.map((alert, i) => <p className="alert" key={i}><ShieldAlert />{alert.message}</p>) : <Empty text="没有待处理告警。" />}</div></section><section className="csm-grid two"><div className="csm-card"><h2>订阅源健康</h2>{data?.sources.map(source => <p key={source.id}><span className={`dot ${source.status}`}></span>{source.name}<small>{source.lastError || pretty(source.lastSuccessAt)}</small></p>)}</div><div className="csm-card"><h2>聚合配置</h2>{data?.profiles.map(profile => <p key={profile.id}><Send />{profile.name}<small>{profile.targetKernel} · {profile.publishedStatus}</small></p>)}</div></section></> }

function ProfileCard({ profile, nodes, ruleSets, action, copy, subscribeUrl }: { profile: Profile; nodes: Node[]; ruleSets: RuleSet[]; action: (work: () => Promise<unknown>, message: string) => Promise<void>; copy: (value: string, message?: string) => Promise<void>; subscribeUrl: (token?: string) => string }) { const [open, setOpen] = useState(false); const [selections, setSelections] = useState<string[]>(profile.selectedStableIdentities || []); const [ruleSetId, setRuleSetId] = useState(profile.ruleSetId || ''); const [preview, setPreview] = useState(''); const url = subscribeUrl(profile.subscriptionToken); const loadPreview = async () => { const payload = await apiPost<{ yaml: string }>(`${base}/profiles/${profile.id}/preview`, {}); setPreview(payload.yaml); }; return <article className="profile"><div><strong>{profile.name}</strong><small>{profile.targetKernel === 'mihomo' ? 'Mihomo / Clash Meta' : '传统 Clash Premium'} · {profile.publishedStatus}</small></div><span className={`pill ${profile.publishedStatus}`}>{profile.publishedAt ? '已发布' : '草稿'}</span><button onClick={() => setOpen(!open)}>编辑</button>{open && <div className="profile-workspace"><label>选择节点（新节点默认不选）<select multiple value={selections} onChange={e => setSelections(Array.from(e.currentTarget.selectedOptions).map(o => o.value))}>{nodes.map(node => <option key={node.id} value={node.stableIdentity} disabled={!node.supportedOutput || (profile.targetKernel === 'clash' && ['vless', 'hysteria', 'hysteria2', 'tuic', 'wireguard'].includes(node.protocol))}>{node.name} · {node.protocol}</option>)}</select></label><button onClick={() => void action(() => apiPut(`${base}/profiles/${profile.id}/selections`, { stableIdentities: selections }), '节点选择已保存。')}>保存节点</button><label>规则库<select value={ruleSetId} onChange={e => setRuleSetId(e.target.value)}><option value="">不使用规则库</option>{ruleSets.map(rule => <option key={rule.id} value={rule.id}>{rule.name}</option>)}</select></label><button onClick={() => void action(() => apiPut(`${base}/profiles/${profile.id}`, { ruleSetId: ruleSetId || null }), '规则库已关联。')}>保存规则库</button><div className="profile-actions"><button onClick={() => void action(() => apiPost(`${base}/profiles/${profile.id}/validate`, {}), '校验完成。')}><Check />校验</button><button onClick={() => void (loadPreview().catch(e => alert(e.message)))}><FileCode2 />预览</button><button className="primary" onClick={() => void action(() => apiPost(`${base}/profiles/${profile.id}/publish`, {}), '已原子发布有效配置。')}><Upload />发布</button></div>{url && <div className="subscription"><code>{url}</code><button onClick={() => void copy(url, '订阅链接已复制。')}><Clipboard /></button><button onClick={() => void action(() => apiPost(`${base}/profiles/${profile.id}/rotate-token`, {}), '令牌已轮换，旧链接已撤销。')}>轮换</button></div>}{preview && <pre>{preview}</pre>}</div>}</article> }

function RulesView({ ruleSets, action }: { ruleSets: RuleSet[]; action: (work: () => Promise<unknown>, message: string) => Promise<void> }) { const [name, setName] = useState(''); const [content, setContent] = useState(''); return <section className="csm-grid two"><form className="csm-card csm-form" onSubmit={e => { e.preventDefault(); void action(() => apiPost(`${base}/rule-sets/import`, { name, content }), '规则库已作为独立副本导入。'); }}><h2><Upload />导入 Clash 规则</h2><label>名称<input required value={name} onChange={e => setName(e.target.value)} /></label><label>YAML 文本<textarea required value={content} onChange={e => setContent(e.target.value)} placeholder={'proxy-groups:\n  - name: PROXY\n    type: select\n    proxies: [DIRECT]\nrules:\n  - MATCH,PROXY'} /></label><button className="primary">导入为可编辑副本</button></form><div className="csm-card"><h2>规则库</h2><div className="csm-list">{ruleSets.map(rule => <article key={rule.id}><div><strong>{rule.name}</strong><small>{rule.rules.length} 条规则 · {rule.groups.length} 个策略组 · {Object.keys(rule.providers).length} 个 Provider</small></div><button className="danger" onClick={() => void action(() => apiDelete(`${base}/rule-sets/${rule.id}`), '规则库已删除。')}><Trash2 /></button></article>)}{!ruleSets.length && <Empty text="规则不会随节点订阅自动导入。" />}</div></div></section> }
function Empty({ text }: { text: string }) { return <p className="empty">{text}</p> }
function pretty(value?: string) { return value ? new Date(value).toLocaleString() : '尚无记录'; }
