import { useState } from 'react';
import type { CSSProperties, ReactNode } from 'react';
import { AlertCircle, CheckCircle, Loader2, X } from 'lucide-react';

export function Alert({ type, children }: { type: 'error' | 'success' | 'info'; children: ReactNode }) { const Icon = type === 'success' ? CheckCircle : AlertCircle; return <div className={`tb-alert ${type}`}><Icon size={16} /><span>{children}</span></div>; }
export function Spin({ size = 16 }: { size?: number }) { return <Loader2 size={size} className="spin" />; }
export function EmptyState({ icon, title, hint }: { icon?: ReactNode; title: string; hint?: string }) { return <div className="tb-empty">{icon && <div>{icon}</div>}<strong>{title}</strong>{hint && <span>{hint}</span>}</div>; }
export function Field({ label, children, full, style }: { label: ReactNode; children: ReactNode; full?: boolean; style?: CSSProperties }) { return <div className={`tb-form-field${full ? ' tb-full-col' : ''}`} style={style}><label>{label}</label>{children}</div>; }
export function Modal({ title, onClose, children, foot, width }: { title: string; onClose: () => void; children: ReactNode; foot?: ReactNode; width?: number }) { return <div className="tb-modal-backdrop" onClick={(event) => event.target === event.currentTarget && onClose()}><div className="tb-modal" style={width ? { width } : undefined}><div className="tb-modal-head"><h3>{title}</h3><button className="tb-btn-icon" type="button" onClick={onClose}><X size={16} /></button></div><div className="tb-modal-body">{children}</div>{foot && <div className="tb-modal-foot">{foot}</div>}</div></div>; }
export function Badge({ children, color = 'default' }: { children: ReactNode; color?: 'default' | 'green' | 'red' | 'blue' | 'amber' }) { return <span className={`tb-badge tb-badge-${color}`}>{children}</span>; }
export function useConfirm() { const [state, setState] = useState<{ title: string; message: ReactNode; onConfirm: () => void } | null>(null); return { confirm: (value: { title: string; message: ReactNode; onConfirm: () => void }) => setState(value), dialog: state && <Modal title={state.title} onClose={() => setState(null)} foot={<><button className="tb-btn tb-btn-secondary" type="button" onClick={() => setState(null)}>取消</button><button className="tb-btn tb-btn-danger" type="button" onClick={() => { state.onConfirm(); setState(null); }}>确认</button></>}><div className="tb-confirm-body">{state.message}</div></Modal> }; }
